### ISSUE TITLE
Alignment legaldocx 

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#31] opened 2015-07-31 07:58 UTC
firm24.docarama.com

When selecting a document, the is a gap between the top menu bar and the start of a legaldoc viewer.
Please align it properly. Button in the bottom is also not clearly visible.
See screenshot
![screen shot 2015-07-31 at 09 55 36](https://cloud.githubusercontent.com/assets/8112173/9003032/b7f59020-376a-11e5-94f1-f9c34d728cc5.png)

**Comment by jurrew27** [comment] 2015-07-31 09:56
Cannot reproduce
![screenshot from 2015-07-31 11 56 17](https://cloud.githubusercontent.com/assets/7300476/9005048/37f53d60-377b-11e5-831b-b31a69d85480.png)

**Comment by jurrew27** [comment] 2015-07-31 10:05
.app-content-full adds 60px to the top to account for the navbar. On staging/production this is somehow unnecessary. Will fix if not fixed on next update already.

**Closed** 2015-07-31 15:48 UTC
Labels: done
